import type { Customer, Store, Case, Task } from "./model";
const customer = (
  id: string,
  name: string,
  health: Customer["health"],
  nextAction: string,
  extra: Partial<Customer> = {},
): Customer => ({
  id,
  name,
  email: `${name
    .toLowerCase()
    .split(" ")[0]
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")}@creator.example`,
  phone: "+549110000" + id.slice(-4),
  handle: "@" + name.toLowerCase().split(" ")[0],
  platforms: ["OnlyFans"],
  owner: "Toti Gauna",
  language: "Español",
  timezone: "America/Argentina/Buenos_Aires",
  health,
  vip: false,
  stage: "Activo",
  sentiment: "Neutral",
  account: { status: "Activo", since: "2026-06-12" },
  subscription: {
    plan: "Plan de ejemplo",
    monthly: 89,
    discount: "",
    discountStart: "",
    discountEnd: "",
  },
  preference: {
    channel: "Email",
    notes: "Preferencia de ejemplo; confirmar antes de contactar.",
  },
  lastContact: "2026-10-06",
  nextAction,
  nextDate: nextAction ? "2026-10-08" : "",
  notes:
    "Cliente ficticio para práctica. Los planes y valores no representan una oferta real de Traqeer.",
  ...extra,
});
const makeCase = (
  id: string,
  customerId: string,
  title: string,
  category: string,
  priority: Case["priority"],
  facts: string,
  extra: Partial<Case> = {},
): Case => ({
  id,
  customerId,
  title,
  category,
  priority,
  facts,
  description: facts,
  hypothesis: "",
  status: "Abierto",
  owner: "Toti Gauna",
  created: "2026-10-05",
  updated: "2026-10-07",
  nextUpdate: "2026-10-08",
  evidence: [],
  customerStatus: "Recibido; pendiente de investigación y actualización.",
  resolution: "",
  resolvedAt: "",
  ...extra,
});
const task = (
  id: string,
  customerId: string,
  title: string,
  priority: Task["priority"],
  due: string,
  extra: Partial<Task> = {},
): Task => ({
  id,
  customerId,
  title,
  priority,
  due,
  owner: "Toti Gauna",
  type: "Seguimiento",
  status: "Por hacer",
  caseId: "",
  paymentId: "",
  leadId: "",
  recurrence: 0,
  ...extra,
});
export function createSeed(): Store {
  return {
    version: 1,
    revision: "seed-v1",
    config: {
      referenceDate: "2026-10-08",
      inactiveDays: 30,
      stuckDays: 60,
      sequenceDays: [0, 3, 10],
      alerts: {
        overdue: true,
        vip: true,
        promise: true,
        recurrence: true,
        quality: true,
        inactivity: true,
      },
      role: "operator",
    },
    customers: [
      customer(
        "TQ-1001",
        "María Torres",
        "risk",
        "Solicitar una fecha concreta de pago",
        {
          lastContact: "2026-09-28",
          nextDate: "2026-10-07",
          sentiment: "Preocupada",
          notes:
            "Debe dos meses: USD 178. Primer recordatorio hace 10 días. Respondió: “Sí, esta semana lo veo.” Servicio activo. No hay fecha concreta de compromiso.",
        },
      ),
      customer(
        "TQ-1002",
        "Alex Morgan",
        "churn",
        "Actualizar al VIP sobre la investigación",
        {
          vip: true,
          platforms: ["OnlyFans", "Instagram"],
          language: "English",
          timezone: "America/New_York",
          email: "alex@creator.example",
          phone: "+12025550102",
          lastContact: "2026-10-07",
          nextDate: "2026-10-08",
          sentiment: "Frustrado",
          subscription: {
            plan: "VIP · ejemplo",
            monthly: 349,
            discount: "",
            discountStart: "",
            discountEnd: "",
          },
          notes:
            "Creator ficticio US, alrededor de 300k seguidores. Amenaza con cambiar de servicio. 240 enlaces removidos registrados en octubre; eso no demuestra que su problema esté resuelto.",
        },
      ),
      customer(
        "TQ-1003",
        "Sofía Luna",
        "risk",
        "Investigar la tercera recurrencia",
        { sentiment: "Frustrada", lastContact: "2026-10-07" },
      ),
      customer(
        "TQ-1004",
        "Cami Ríos",
        "churn",
        "Verificar el cargo de USD 89 frente a USD 45",
        {
          sentiment: "Frustrada",
          nextDate: "2026-10-07",
          notes:
            "La cliente esperaba USD 45 y reporta un cargo de USD 89. Discrepancia sin conciliar; ningún reembolso autorizado.",
        },
      ),
      customer(
        "TQ-1005",
        "Agus Vega",
        "watch",
        "Orientar el reporte y registrar su referido",
      ),
      customer(
        "TQ-1006",
        "Flor Medina",
        "watch",
        "Confirmar inicio y vencimiento del descuento",
        {
          subscription: {
            plan: "Plan de ejemplo",
            monthly: 89,
            discount:
              "Descuento de 3 meses reportado por la cliente. Fechas sin confirmar.",
            discountStart: "",
            discountEnd: "",
          },
          nextDate: "2026-10-09",
        },
      ),
      customer(
        "TQ-1007",
        "Meli Costa",
        "risk",
        "Pedir evidencia del grupo y revisar su caso",
        { sentiment: "Decepcionada", platforms: ["OnlyFans", "Fansly"] },
      ),
      customer(
        "TQ-1008",
        "Vale Romero",
        "watch",
        "Confirmar el nuevo email y canal preferido",
        {
          email: "vale.old@creator.example",
          preference: {
            channel: "WhatsApp",
            notes:
              "Solicitó cambiar a vale.new@creator.example. Confirmar antes de modificar. La entrega por WhatsApp requiere confirmar integración.",
          },
          nextDate: "2026-10-09",
        },
      ),
      customer("TQ-1009", "Lucía Díaz", "healthy", "", {
        vip: true,
        subscription: {
          plan: "VIP · ejemplo",
          monthly: 249,
          discount: "",
          discountStart: "",
          discountEnd: "",
        },
        lastContact: "2026-10-04",
        sentiment: "Positiva",
      }),
      customer("TQ-1010", "Emma Wilson", "healthy", "", {
        language: "English",
        timezone: "Europe/London",
        phone: "+447700900123",
        subscription: {
          plan: "Plan de ejemplo",
          monthly: 89,
          discount: "",
          discountStart: "",
          discountEnd: "",
        },
      }),
      customer(
        "TQ-1011",
        "Nina Santos",
        "healthy",
        "Revisar el pago comprometido",
        {
          nextDate: "2026-10-07",
          lastContact: "2026-10-04",
          notes:
            "Caso adicional ficticio: prometió explícitamente pagar USD 89 el 6 de octubre. Se usa para practicar compromisos incumplidos.",
        },
      ),
      customer("TQ-1012", "Laura Pérez", "healthy", "", {
        lastContact: "2026-10-01",
      }),
    ],
    tasks: [
      task(
        "TASK-001",
        "TQ-1002",
        "Dar una actualización concreta a Alex",
        "critical",
        "2026-10-08",
        { caseId: "CASE-001", type: "VIP / retención" },
      ),
      task(
        "TASK-002",
        "TQ-1001",
        "Pedir una fecha de pago a María",
        "high",
        "2026-10-07",
        { paymentId: "PAY-001", type: "Cobranza" },
      ),
      task(
        "TASK-003",
        "TQ-1003",
        "Investigar el video que reapareció por tercera vez",
        "high",
        "2026-10-08",
        {
          caseId: "CASE-002",
          owner: "Equipo de investigación",
          type: "Investigación",
        },
      ),
      task(
        "TASK-004",
        "TQ-1004",
        "Verificar el cargo reportado por Cami",
        "high",
        "2026-10-07",
        { caseId: "CASE-003", type: "Facturación" },
      ),
      task(
        "TASK-005",
        "TQ-1005",
        "Explicar cómo reportar los nuevos enlaces",
        "medium",
        "2026-10-08",
        { caseId: "CASE-004" },
      ),
      task(
        "TASK-006",
        "TQ-1006",
        "Confirmar las fechas del descuento con supervisión",
        "medium",
        "2026-10-09",
        { caseId: "CASE-005", status: "Esperando equipo" },
      ),
      task(
        "TASK-007",
        "TQ-1007",
        "Pedir el enlace o la captura del grupo",
        "high",
        "2026-10-08",
        { caseId: "CASE-006" },
      ),
      task(
        "TASK-008",
        "TQ-1008",
        "Confirmar el cambio de email solicitado",
        "medium",
        "2026-10-09",
        { caseId: "CASE-007" },
      ),
      task(
        "TASK-009",
        "",
        "Segundo contacto de Romina: abrir conversación",
        "medium",
        "2026-10-08",
        { leadId: "LEAD-001", type: "Outreach" },
      ),
      task(
        "TASK-010",
        "TQ-1011",
        "Revisar el compromiso de pago incumplido",
        "high",
        "2026-10-07",
        { paymentId: "PAY-003" },
      ),
      task(
        "TASK-011",
        "TQ-1009",
        "Revisión semanal de la cuenta de Lucía",
        "low",
        "2026-10-12",
        { recurrence: 7, type: "Revisión" },
      ),
      task(
        "TASK-012",
        "TQ-1008",
        "Registrar la solicitud de actualización de datos",
        "medium",
        "2026-10-06",
        { status: "Completada" },
      ),
    ],
    cases: [
      makeCase(
        "CASE-001",
        "TQ-1002",
        "VIP con intención de cambiar de servicio",
        "Riesgo de baja",
        "critical",
        "Alex sigue encontrando contenido en Telegram y expresa intención de cambiar de servicio. Hay 240 remociones registradas este mes.",
        {
          evidence: ["https://evidence.example/alex/telegram-report"],
          hypothesis:
            "Podrían ser nuevas publicaciones o redistribuciones; pendiente de investigación.",
          owner: "Equipo de investigación",
          status: "Investigando",
        },
      ),
      makeCase(
        "CASE-002",
        "TQ-1003",
        "Tercera aparición del mismo video",
        "Piratería recurrente",
        "high",
        "Sofía indica que el mismo video reapareció en el mismo canal por tercera vez.",
        {
          evidence: ["https://evidence.example/sofia/recurrence-3"],
          hypothesis:
            "Posible redistribución posterior a una remoción. No confirmado.",
          status: "Investigando",
          owner: "Equipo de investigación",
        },
      ),
      makeCase(
        "CASE-003",
        "TQ-1004",
        "Cargo de $89 frente a $45 esperado",
        "Facturación",
        "high",
        "Cami reporta un cargo de USD 89 y esperaba USD 45. Dice que no recibió aviso y puede irse.",
      ),
      makeCase(
        "CASE-004",
        "TQ-1005",
        "Dudas para reportar un nuevo sitio",
        "Reporte de contenido",
        "medium",
        "Agus encontró enlaces en un sitio nuevo y no sabe dónde reportarlos. Además menciona una amiga interesada.",
      ),
      makeCase(
        "CASE-005",
        "TQ-1006",
        "Descuento sin fechas confirmadas",
        "Descuento",
        "medium",
        "Flor recuerda un descuento por 3 meses pero desconoce su inicio y vencimiento.",
        { nextUpdate: "2026-10-09", status: "Esperando equipo" },
      ),
      makeCase(
        "CASE-006",
        "TQ-1007",
        "Contenido en un grupo desconocido",
        "Insatisfacción",
        "high",
        "Un fan envió una captura de un grupo de Telegram. Meli cuestiona el valor del servicio y la suficiencia del plan.",
      ),
      makeCase(
        "CASE-007",
        "TQ-1008",
        "Reporte enviado al email anterior",
        "Datos de contacto",
        "medium",
        "Vale reporta que el informe fue enviado al email antiguo y solicita actualizar contacto y confirmar entrega por WhatsApp.",
        { nextUpdate: "2026-10-09" },
      ),
      makeCase(
        "CASE-008",
        "TQ-1009",
        "Consulta de reporte mensual",
        "Usabilidad",
        "low",
        "Consulta ficticia respondida; la cliente confirmó comprensión.",
        {
          created: "2026-10-01",
          updated: "2026-10-03",
          nextUpdate: "",
          status: "Resuelto",
          resolution:
            "Se registró la orientación y la confirmación de la cliente.",
          resolvedAt: "2026-10-03",
        },
      ),
    ],
    payments: [
      {
        id: "PAY-001",
        reference: "INV-MARIA-AUG",
        customerId: "TQ-1001",
        amount: 89,
        due: "2026-08-01",
        status: "Pendiente",
        receivedAt: "",
        lastAttempt: "2026-09-28",
        lastPayment: "2026-07-01",
        promiseDate: "",
        promiseText: "“Sí, esta semana lo veo.” Sin fecha concreta.",
      },
      {
        id: "PAY-002",
        reference: "INV-MARIA-SEP",
        customerId: "TQ-1001",
        amount: 89,
        due: "2026-09-01",
        status: "Pendiente",
        receivedAt: "",
        lastAttempt: "2026-09-28",
        lastPayment: "2026-07-01",
        promiseDate: "",
        promiseText: "",
      },
      {
        id: "PAY-003",
        reference: "INV-NINA-SEP",
        customerId: "TQ-1011",
        amount: 89,
        due: "2026-09-01",
        status: "Pendiente",
        receivedAt: "",
        lastAttempt: "2026-10-04",
        lastPayment: "2026-08-01",
        promiseDate: "2026-10-06",
        promiseText: "Pagaré los USD 89 el 6 de octubre.",
      },
      {
        id: "PAY-004",
        reference: "INV-LUCIA-OCT",
        customerId: "TQ-1009",
        amount: 249,
        due: "2026-10-01",
        status: "Recibido",
        receivedAt: "2026-10-01",
        lastAttempt: "",
        lastPayment: "2026-10-01",
        promiseDate: "",
        promiseText: "",
      },
      {
        id: "PAY-005",
        reference: "INV-EMMA-OCT",
        customerId: "TQ-1010",
        amount: 89,
        due: "2026-10-01",
        status: "Recibido",
        receivedAt: "2026-10-01",
        lastAttempt: "",
        lastPayment: "2026-10-01",
        promiseDate: "",
        promiseText: "",
      },
    ],
    interactions: [
      {
        id: "INT-001",
        customerId: "TQ-1001",
        channel: "WhatsApp",
        kind: "contact",
        text: "Primer recordatorio de los dos meses pendientes. Se pidió confirmar cuándo puede pagar.",
        date: "2026-09-28T14:00:00Z",
        author: "Toti Gauna",
      },
      {
        id: "INT-002",
        customerId: "TQ-1001",
        channel: "WhatsApp",
        kind: "incoming",
        text: "Sí, esta semana lo veo.",
        date: "2026-09-28T16:00:00Z",
        author: "María Torres",
      },
      {
        id: "INT-003",
        customerId: "TQ-1002",
        channel: "Email",
        kind: "incoming",
        text: "guys this is a mess, I keep finding my content on Telegram, what am I even paying for, I'm switching to another service",
        date: "2026-10-07T17:20:00Z",
        author: "Alex Morgan",
      },
      {
        id: "INT-004",
        customerId: "TQ-1002",
        channel: "Internal note",
        kind: "note",
        text: "Hecho: 240 remociones registradas en octubre. La preocupación sigue abierta. Pedir enlaces concretos y coordinar una actualización, sin garantizar la resolución.",
        date: "2026-10-07T18:00:00Z",
        author: "Toti Gauna",
      },
      {
        id: "INT-005",
        customerId: "TQ-1003",
        channel: "Telegram",
        kind: "incoming",
        text: "El mismo video está otra vez en el mismo canal. Ya es la tercera vez, me cansé de reportarlo.",
        date: "2026-10-07T15:00:00Z",
        author: "Sofía Luna",
      },
      {
        id: "INT-006",
        customerId: "TQ-1004",
        channel: "Email",
        kind: "incoming",
        text: "Me cobraron 89 en vez de 45 y nadie me avisó. Si sigue así, me voy.",
        date: "2026-10-06T11:00:00Z",
        author: "Cami Ríos",
      },
      {
        id: "INT-007",
        customerId: "TQ-1008",
        channel: "WhatsApp",
        kind: "incoming",
        text: "El reporte llegó al email viejo. ¿Pueden actualizarlo y enviarlo también por WhatsApp?",
        date: "2026-10-06T15:00:00Z",
        author: "Vale Romero",
      },
      {
        id: "INT-008",
        customerId: "TQ-1006",
        channel: "Email",
        kind: "incoming",
        text: "Me habían dicho 3 meses de descuento. ¿Cuándo terminan? No quiero otro cargo inesperado.",
        date: "2026-10-06T12:00:00Z",
        author: "Flor Medina",
      },
    ],
    escalations: [
      {
        id: "ESC-001",
        customerId: "TQ-1002",
        caseId: "CASE-001",
        reason:
          "VIP con intención explícita de cambiar a un competidor; investigación y actualización prioritaria.",
        owner: "Equipo de investigación",
        priority: "critical",
        created: "2026-10-07",
        nextUpdate: "2026-10-08",
        status: "Pendiente",
        approval: true,
      },
      {
        id: "ESC-002",
        customerId: "TQ-1004",
        caseId: "CASE-003",
        reason:
          "Validar el cargo y la expectativa de precio. Cualquier compensación requiere política y aprobación.",
        owner: "Revisión de supervisión",
        priority: "high",
        created: "2026-10-06",
        nextUpdate: "2026-10-07",
        status: "En revisión",
        approval: true,
      },
    ],
    leads: [
      {
        id: "LEAD-001",
        name: "Romina Acosta",
        email: "romina@prospect.example",
        platform: "OnlyFans",
        audience: 300,
        source: "Prospección · ejercicio",
        pain: "Ya encontró contenido distribuido fuera de la plataforma.",
        objection:
          "Su contenido es genérico y duda de cómo se podría identificar.",
        stage: "Contactado",
        owner: "Toti Gauna",
        lastContact: "2026-10-05",
        nextContact: "2026-10-08",
        handoff: "",
        notes:
          "Secuencia de ejemplo: contacto inicial 05/10, seguimiento 08/10, último seguimiento 15/10. Objetivo: iniciar conversación.",
      },
      {
        id: "LEAD-002",
        name: "Dani Ferreira",
        email: "",
        platform: "OnlyFans",
        audience: 0,
        source: "Referida por Agus",
        pain: "Le preocupa la redistribución de su contenido.",
        objection: "Por confirmar",
        stage: "Nuevo",
        owner: "Toti Gauna",
        lastContact: "",
        nextContact: "2026-10-09",
        handoff: "",
        notes: "Confirmar permiso para contacto y obtener datos mínimos.",
      },
      {
        id: "LEAD-003",
        name: "Julia Reyes",
        email: "julia@prospect.example",
        platform: "Fansly",
        audience: 1200,
        source: "Referido ficticio",
        pain: "Solicita información sobre protección de contenido.",
        objection: "Quiere entender alcance real antes de decidir.",
        stage: "Interesado",
        owner: "Toti Gauna",
        lastContact: "2026-10-07",
        nextContact: "2026-10-08",
        handoff: "",
        notes: "Datos ficticios. No se prometió un nivel de remoción.",
      },
    ],
    incidents: [
      {
        id: "INC-001",
        customerId: "TQ-1002",
        caseId: "CASE-001",
        title: "Contenido reportado en Telegram",
        channel: "Telegram",
        evidence: "https://evidence.example/alex/telegram-report",
        date: "2026-10-07",
        recurrence: 2,
      },
      {
        id: "INC-002",
        customerId: "TQ-1003",
        caseId: "CASE-002",
        title: "Mismo video, mismo canal",
        channel: "Telegram",
        evidence: "https://evidence.example/sofia/recurrence-3",
        date: "2026-10-07",
        recurrence: 3,
      },
      {
        id: "INC-003",
        customerId: "TQ-1007",
        caseId: "CASE-006",
        title: "Captura de grupo no identificado",
        channel: "Telegram",
        evidence: "",
        date: "2026-10-06",
        recurrence: 1,
      },
    ],
    removals: [
      {
        id: "REM-001",
        customerId: "TQ-1002",
        incidentId: "INC-001",
        date: "2026-10-01",
        count: 28,
      },
      {
        id: "REM-002",
        customerId: "TQ-1002",
        incidentId: "INC-001",
        date: "2026-10-02",
        count: 36,
      },
      {
        id: "REM-003",
        customerId: "TQ-1002",
        incidentId: "INC-001",
        date: "2026-10-03",
        count: 24,
      },
      {
        id: "REM-004",
        customerId: "TQ-1002",
        incidentId: "INC-001",
        date: "2026-10-04",
        count: 42,
      },
      {
        id: "REM-005",
        customerId: "TQ-1002",
        incidentId: "INC-001",
        date: "2026-10-05",
        count: 38,
      },
      {
        id: "REM-006",
        customerId: "TQ-1002",
        incidentId: "INC-001",
        date: "2026-10-06",
        count: 40,
      },
      {
        id: "REM-007",
        customerId: "TQ-1002",
        incidentId: "INC-001",
        date: "2026-10-07",
        count: 32,
      },
      {
        id: "REM-008",
        customerId: "TQ-1003",
        incidentId: "INC-002",
        date: "2026-10-02",
        count: 1,
      },
    ],
    rawRecords: [
      {
        id: "RAW-001",
        phone: "+5491133344455",
        name: "Carolina M.",
        stage: "impago",
        lastContact: "28/09/2026",
        nextAction: "Mensaje de cobro",
        nextDate: "05/10/2026",
        amount: "89",
        review: "",
      },
      {
        id: "RAW-002",
        phone: "11-5566-7788",
        name: "Romina T.",
        stage: "en conversación",
        lastContact: "03/15/2026",
        nextAction: "Enviar propuesta",
        nextDate: "08/10/2026",
        amount: "156",
        review: "",
      },
      {
        id: "RAW-003",
        phone: "+5491133344455",
        name: "Caro Molinari",
        stage: "impago",
        lastContact: "29/09/2026",
        nextAction: "Llamada de cobro",
        nextDate: "06/10/2026",
        amount: "120",
        review: "",
      },
      {
        id: "RAW-004",
        phone: "+573001112233",
        name: "Vanessa R.",
        stage: "dormido",
        lastContact: "31/02/2026",
        nextAction: "Mensaje de reactivación",
        nextDate: "",
        amount: "45",
        review: "",
      },
      {
        id: "RAW-005",
        phone: "+5215566778899",
        name: "Pau G.",
        stage: "ganado",
        lastContact: "01/10/2026",
        nextAction: "",
        nextDate: "",
        amount: "1.200",
        review: "",
      },
      {
        id: "RAW-006",
        phone: "+447700900123",
        name: "Emma W.",
        stage: "en conversación",
        lastContact: "02/10/2026",
        nextAction: "Responder consulta de precios",
        nextDate: "20/01/2026",
        amount: "89",
        review: "",
      },
    ],
    playbooks: [
      {
        id: "PB-001",
        title: "Procedimientos de pago",
        marker: "[CONFIRM AUTHORIZED PAYMENT OPTION]",
        body: "Solicitar una fecha concreta, registrar la respuesta y programar seguimiento. No ofrecer financiación, créditos, descuentos o suspensión sin autorización.",
        status: "Por confirmar",
      },
      {
        id: "PB-002",
        title: "Escalaciones",
        marker: "[CONFIRM ESCALATION SLA]",
        body: "Registrar motivo, prioridad, responsable y próxima actualización. Confirmar equipo y tiempos autorizados. Una solicitud registrada no es una aprobación.",
        status: "Por confirmar",
      },
      {
        id: "PB-003",
        title: "Clientes VIP",
        marker: "[COMPANY POLICY REQUIRED]",
        body: "Reconocer frustración y asumir seguimiento. Compartir hechos registrados sin ponerse a la defensiva. Pedir evidencia relevante y fijar próxima actualización. No garantizar resolución inmediata.",
        status: "Por confirmar",
      },
      {
        id: "PB-004",
        title: "Facturación y descuentos",
        marker: "[SUPERVISOR APPROVAL REQUIRED]",
        body: "Validar cargo, expectativa, inicio y fin del descuento. No adivinar fechas ni emitir compensaciones. Confirmar la política con supervisión.",
        status: "Por confirmar",
      },
      {
        id: "PB-005",
        title: "Reportar contenido",
        marker: "[COMPANY POLICY REQUIRED]",
        body: "Confirmar el canal oficial y el procedimiento de reporte. Recopilar enlaces o evidencia mínima necesaria. No inventar un portal o una capacidad de detección.",
        status: "Por confirmar",
      },
      {
        id: "PB-006",
        title: "Comunicación con clientes",
        marker: "[COMPANY POLICY REQUIRED]",
        body: "Los textos son borradores de práctica. Confirmar preferencias y canales disponibles. Registrar compromisos del cliente y del equipo por separado.",
        status: "Por confirmar",
      },
      {
        id: "PB-007",
        title: "Outreach y referidos",
        marker: "[COMPANY POLICY REQUIRED]",
        body: "Abrir conversación con empatía y preguntas concretas sobre el problema. Secuencia de ejemplo: día 0, día 3, día 10. Confirmar consentimiento y respetar no contactar.",
        status: "Por confirmar",
      },
      {
        id: "PB-008",
        title: "Privacidad y reglas CRM",
        marker: "[COMPANY POLICY REQUIRED]",
        body: "Minimizar datos, revisar contactos y preservar información de origen. No fusionar duplicados automáticamente. Este prototipo local solo debe contener datos ficticios.",
        status: "Por confirmar",
      },
    ],
    audit: [],
  };
}
